BEGIN
     DBMS_SCHEDULER.SET_ATTRIBUTE (
     'MTK_TICKET_PROTOCOLO', 
     'job_action', 
     'BEGIN EXECUTE IMMEDIATE ''DROP SEQUENCE SEQ_MTK_TICKET_PROTOCOLO''; EXECUTE IMMEDIATE ''CREATE SEQUENCE SEQ_MTK_TICKET_PROTOCOLO minvalue 1 maxvalue 999999 increment by 1 cache 20''; EXECUTE IMMEDIATE ''DELETE FROM MTK_NOTIFICACAO WHERE LIDO = 1''; END;'
     );
END;