CREATE OR REPLACE TRIGGER TR_TICKETPROTOCOLO
  BEFORE INSERT ON MTK_TICKET
  FOR EACH ROW
DECLARE
  V_PROTOCOLO VARCHAR2(20);
BEGIN
  SELECT TO_CHAR(SYSDATE, 'MMYY') || LPAD(SEQ_MTK_TICKET_PROTOCOLO.NEXTVAL, 6, '0')
         INTO V_PROTOCOLO
         FROM DUAL;

  :NEW.PROTOCOLO := V_PROTOCOLO;
END TR_TICKETPROTOCOLO;
