CREATE OR REPLACE view view_bdc_artigo_busca as
SELECT A.ID, 
       A.TITULO,
       A.DATA_VIGENCIA_INICIO,
       A.DATA_VIGENCIA_FIM,
       C.NOME AS CATEGORIA_NOME,
       C.DESCRICAO AS CATEGORIA_DESCRICAO,
       S.NOME AS SECAO_NOME,
       S.DESCRICAO AS SECAO_DESCRICAO,  
       (SELECT LISTAGG(PALAVRA_CHAVE,',') WITHIN GROUP (ORDER BY PALAVRA_CHAVE) 
        FROM BDC_ARTIGO_PALAVRA
        WHERE BDC_ARTIGO_PALAVRA.ID_ARTIGO = A.ID
       ) AS PALAVRAS_CHAVE,
       (CASE A.PERFIL_VISUALIZACAO
         WHEN NULL THEN S.PERFIL_VISUALIZACAO
         ELSE
         A.PERFIL_VISUALIZACAO
       END)
       AS PERFIL_VISUALIZACAO,
       STATUS
       
FROM BDC_ARTIGO A

LEFT JOIN BDC_SECAO S ON 
A.ID_SECAO = S.ID

LEFT JOIN BDC_CATEGORIA C ON
C.ID = S.ID_CATEGORIA

WHERE STATUS = 1 --Somente aprovados
