CREATE OR REPLACE VIEW VIEW_BDC_ARTIGO_BUSCA_CONTEUDO AS
SELECT A.ID,
       A.TITULO,
       A.DATA_VIGENCIA_INICIO,
       A.DATA_VIGENCIA_FIM,
       A.PERFIL_VISUALIZACAO,
       A.STATUS,       
       LISTAGG(P.PALAVRA_CHAVE) WITHIN GROUP (ORDER BY A.ID) AS PALAVRAS
FROM BDC_ARTIGO A
INNER JOIN BDC_SECAO S ON
      A.ID_SECAO = S.ID
INNER JOIN BDC_ARTIGO_PALAVRA P ON
      A.ID = P.ID_ARTIGO
WHERE A.STATUS = 1 --Somente aprovados
GROUP BY A.ID, 
         A.TITULO,       
         A.DATA_VIGENCIA_INICIO,
         A.DATA_VIGENCIA_FIM,
         A.PERFIL_VISUALIZACAO,
         A.STATUS
