--// @c:\Users\alessandro.augusto\Documents\SQL\ATUALIZA_GERENCIAL_ITINERARIO.Sql;
CREATE OR REPLACE Procedure ATUALIZA_GERENCIAL_ITINERARIO(P_QTDEUPDADE OUT NUMBER
                                                         ,P_QTDDELETE OUT NUMBER
                                                         ,P_QTDINSERT OUT NUMBER
                                                         ,P_TEMPO OUT VARCHAR2) 
IS
  CURSOR C_LISTA IS
    SELECT B.INTEGRADO_GFO
         , B.COD_INTESCALA
         , B.DAT_ESCALA        
         , B.COD_INTSERVDIARIA 
         , B.COD_HORDIARIA     
         , B.COD_INTTURNO
         , B.FLG_SENTIDO
         , A.COD_INTLINHA
         , B.HOR_SAIDA
      FROM T_ESC_ESCALADIARIA  A
         , T_ESC_HORARIODIARIA B
     WHERE A.COD_INTESCALA = B.COD_INTESCALA
       AND A.DAT_ESCALA    = B.DAT_ESCALA
       AND B.INTEGRADO_GFO = 'S'
       AND A.DAT_ESCALA BETWEEN '02-jul-2010'
                            AND '02-jul-2010'
    ORDER BY B.DAT_ESCALA
      ;
      
R_ITEM       C_LISTA%ROWTYPE;
V_QTDINSERT  NUMBER;
V_DATAESCALA DATE;
V_TEMPOINI   DATE;
V_TEMPOFIM   DATE;

BEGIN
  P_QTDEUPDADE := 0;
  P_QTDDELETE  := 0;
  P_QTDINSERT  := 0;  
  V_TEMPOINI   := SYSDATE;
  OPEN C_LISTA;
  FETCH C_LISTA INTO R_ITEM;

  V_DATAESCALA := R_ITEM.DAT_ESCALA;
  WHILE (C_LISTA%FOUND) LOOP
    /*UPDATE T_ESC_HORARIODIARIA
       SET INTEGRADO_GFO     ='N'
     WHERE DAT_ESCALA        = R_ITEM.DAT_ESCALA
       AND INTEGRADO_GFO     = 'S'
       AND COD_INTSERVDIARIA = R_ITEM.COD_INTSERVDIARIA
       AND COD_HORDIARIA     = R_ITEM.COD_HORDIARIA
       AND COD_INTTURNO      = R_ITEM.COD_INTTURNO
       AND COD_INTESCALA     = R_ITEM.COD_INTESCALA
       AND FLG_SENTIDO       = R_ITEM.FLG_SENTIDO;*/
    
    P_QTDEUPDADE := P_QTDEUPDADE + 1;
    FETCH C_LISTA INTO R_ITEM;
    
    IF (C_LISTA%NOTFOUND OR V_DATAESCALA <> R_ITEM.DAT_ESCALA) THEN
     /* DELETE GFO_GERENCIAL_ITINERARIO A
       WHERE DATAESCALA  = V_DATAESCALA;
      COMMIT;*/
      
      V_QTDINSERT:= 0;
      /*PRGFO_CONVERTEESCALA_GFO(V_DATAESCALA
                              ,TO_DATE(to_char(V_DATAESCALA,'DD/MM/YYYY')|| ' 23:59:59','DD/MM/YYYY HH24:MI:SS')
                              ,TO_DATE(to_char(V_DATAESCALA,'DD/MM/YYYY')|| ' 23:59:59','DD/MM/YYYY HH24:MI:SS')
                              ,V_QTDINSERT);*/
      P_QTDINSERT   := P_QTDINSERT + V_QTDINSERT;
      P_QTDDELETE   := P_QTDDELETE + 1;
      
      V_DATAESCALA := R_ITEM.DAT_ESCALA;      
      IF (C_LISTA%NOTFOUND) THEN         
        EXIT;
      END IF;  
    END IF;  
  
  END LOOP;
  
  CLOSE C_LISTA;

  V_TEMPOFIM := SYSDATE;
  P_TEMPO    := fu_difdatas(V_TEMPOINI ,V_TEMPOFIM,0);
END;
/
--EXECUTE ATUALIZA_GERENCIAL_ITINERARIO
--COMMIT;
--DROP PROCEDURE ATUALIZA_GERENCIAL_ITINERARIO;

