/*

DROP USER WEB_ACIDENTE_ADM CASCADE;
DROP USER WEB_ACIDENTE     CASCADE;

*/

CREATE USER WEB_ACIDENTE_ADM IDENTIFIED BY WEB_ACIDENTE_ADM;
GRANT UNLIMITED TABLESPACE
    , GRANT ANY PRIVILEGE
    , CONNECT
    , CREATE USER
    , CREATE SESSION
    , CREATE TRIGGER 
    , CREATE SEQUENCE 
    , CREATE PROCEDURE 
    , CREATE TABLE
    , CREATE SYNONYM 
    , SELECT ANY SEQUENCE
    , SELECT ANY TABLE
    , INSERT ANY TABLE
    , UPDATE ANY TABLE
    , DELETE ANY TABLE
   TO WEB_ACIDENTE_ADM;
CREATE OR REPLACE SYNONYM WEB_ACIDENTE_ADM.FORMULA                FOR ACD_FORMULA;
CREATE OR REPLACE SYNONYM WEB_ACIDENTE_ADM.VW_FUNCIONARIO         FOR vw_funcionarios;
CREATE OR REPLACE SYNONYM WEB_ACIDENTE_ADM.S_ACD_CONTROLE_RA		  FOR SEQ_CONTROLE;  
CREATE OR REPLACE SYNONYM WEB_ACIDENTE_ADM.VIM_CONCSALDO_ACDESC		FOR RETORNAR_SALDO;


CREATE USER WEB_ACIDENTE IDENTIFIED BY WEB_ACIDENTE;
GRANT UNLIMITED TABLESPACE
    , CONNECT
    , CREATE SYNONYM 
    , SELECT ANY SEQUENCE
    , SELECT ANY TABLE
    , INSERT ANY TABLE
    , UPDATE ANY TABLE
    , DELETE ANY TABLE
   TO WEB_ACIDENTE;

CREATE OR REPLACE SYNONYM WEB_ACIDENTE.FORMULA                FOR ACD_FORMULA;
CREATE OR REPLACE SYNONYM WEB_ACIDENTE.VW_FUNCIONARIO         FOR vw_funcionarios;
CREATE OR REPLACE SYNONYM WEB_ACIDENTE.S_ACD_CONTROLE_RA		  FOR SEQ_CONTROLE;  
CREATE OR REPLACE SYNONYM WEB_ACIDENTE.VIM_CONCSALDO_ACDESC		FOR RETORNAR_SALDO;
