
Select Sys_Context('USERENV', 'ACTION')
      ,Sys_Context('USERENV', 'AUDITED_CURSORID')
      ,Sys_Context('USERENV', 'AUTHENTICATION_DATA')
      ,Sys_Context('USERENV', 'AUTHENTICATION_TYPE')
      ,Sys_Context('USERENV', 'BG_JOB_ID')
      ,Sys_Context('USERENV', 'CLIENT_IDENTIFIER')
      ,Sys_Context('USERENV', 'CLIENT_INFO')
      ,Sys_Context('USERENV', 'CURRENT_SCHEMA')
      ,Sys_Context('USERENV', 'CURRENT_SCHEMAID')
      ,Sys_Context('USERENV', 'CURRENT_SQL')
      ,Sys_Context('USERENV', 'CURRENT_SQLn')
      ,Sys_Context('USERENV', 'CURRENT_USER')
      ,Sys_Context('USERENV', 'CURRENT_USERID')
      ,Sys_Context('USERENV', 'DB_DOMAIN')
      ,Sys_Context('USERENV', 'DB_NAME')
      ,Sys_Context('USERENV', 'DB_UNIQUE_NAME')
      ,Sys_Context('USERENV', 'ENTRYID')
      ,Sys_Context('USERENV', 'EXTERNAL_NAME')
      ,Sys_Context('USERENV', 'FG_JOB_ID')
      ,Sys_Context('USERENV', 'GLOBAL_CONTEXT_MEMORY')
      ,Sys_Context('USERENV', 'HOST')
      ,Sys_Context('USERENV', 'INSTANCE')
      ,Sys_Context('USERENV', 'IP_ADDRESS')
      ,Sys_Context('USERENV', 'ISDBA')
      ,Sys_Context('USERENV', 'LANG')
      ,Sys_Context('USERENV', 'LANGUAGE')
      ,Sys_Context('USERENV', 'MODULE')
      ,Sys_Context('USERENV', 'NETWORK_PROTOCOL')
      ,Sys_Context('USERENV', 'NLS_CALENDAR')
      ,Sys_Context('USERENV', 'NLS_CURRENCY')
      ,Sys_Context('USERENV', 'NLS_DATE_FORMAT')
      ,Sys_Context('USERENV', 'NLS_DATE_LANGUAGE')
      ,Sys_Context('USERENV', 'NLS_SORT')
      ,Sys_Context('USERENV', 'NLS_TERRITORY')
      ,Sys_Context('USERENV', 'OS_USER')
      ,Sys_Context('USERENV', 'PROXY_USER')
      ,Sys_Context('USERENV', 'PROXY_USERID')
      ,Sys_Context('USERENV', 'SERVICE_NAME')
      ,Sys_Context('USERENV', 'SESSION_USER')
      ,Sys_Context('USERENV', 'SESSION_USERID')
      ,Sys_Context('USERENV', 'SESSIONID')
      ,Sys_Context('USERENV', 'STATEMENTID')
      ,Sys_Context('USERENV', 'TERMINAL')
  From Dual
  
  