Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (101,'SEM RENDIC',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (102,'TRANST/DESV',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (103,'AFIRMATIVO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (104,'NEGATIVO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (105,'ADIANTADO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (106,'ATRASADO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (107,'COMBOIO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (110,'INTERVENCAO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (201,'ASSALTO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (202,'ACIDENTE',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (203,'QUED ACIDEN',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (204,'AVARIA LEVE',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (205,'NENHUM',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (206,'VANDALISMO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (207,'VOLANTE',1);
--Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (208,'NENHUM',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (301,'MODULO TRAV',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (302,'PROB BILHET',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (303,'CATRAC TRAV',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (304,'PROB PAGANT',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (305,'PROB IDOSO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (306,'MODULO OK',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (307,'CATRAC OK',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (401,'MECANICO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (402,'COMPRESSOR',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (403,'VAZA AGUA',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (404,'SEM PARTIDA',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (405,'ELETRICO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (406,'PNEU FURADO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (1010,'SEM PLACA',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (1011,'SEM TAB HR',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5111,'AGDE 5 MIN',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5112,'RENDIC PSEC',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5113,'FZ+1 VIAGEM',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5114,'RECOLH BASE',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5121,'ESPECIAL PS',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5122,'AGDE PONTO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5123,'SEGUIR VIAG',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5124,'ADIANTADO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5125,'ATRASADO',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5126,'S CAR FRENTE',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5127,'AUTOR 05 AD',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5128,'TERM VALON',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5129,'ULTRAPASSE',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5130,'INIC ANT TV',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5131,'INIC TS',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5132,'ACERT HORA',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5133,'PF LIG BASE',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5311,'DESL FUSIVL',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5312,'REINICIAR',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5313,'SIGA NORMAL',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5314,'RECOL BASE',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5541,'LIGAR BASE',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5542,'INFORM TABE',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5543,'APÓS LIG BAS',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5544,'ESP  DESEMB',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (5545,'LIGAR 190',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (9901,'MENS 01',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (9902,'MENS 02',1);
Insert Into gfo_mensagens(cod_mensagem,desc_mensagem,tipo_mensagem) Values (9903,'MENS 03',1);
