--Verificar no SAC

SELECT
  A.CODIGOFUNCIONARIO               CODIGO,
  UPPER(P.NOMEABREVIADOFUNCIONARIO) FUNCIONARIO,
  UPPER(A.DIRETORIO)                DIRETORIO,
  UPPER(A.NOMEARQUIVO)              NOME_ARQUIVO,
  TRUNC(A.DATAHORA)                 DATA
FROM
  ARQUIVOS        A, 
  SAC_FUNCIONARIO P
WHERE
  NOT A.CODIGOFUNCIONARIO IS NULL               AND
  P.CODIGOFUNCIONARIO(+)  = A.CODIGOFUNCIONARIO AND
  P.CODIGOFUNCIONARIO IN (
                          '000017' -- Alessandro
                          )
ORDER BY
  UPPER(P.NOMEABREVIADOFUNCIONARIO),
  UPPER(A.NOMEARQUIVO)