CREATE OR REPLACE TRIGGER TR_TESTE_TRIGGER
  AFTER INSERT OR UPDATE OR DELETE ON CTR_MBL_ACESSOS
  FOR EACH ROW
DECLARE
  CONTEUDO  Varchar2(100);
BEGIN
  IF INSERTING THEN
     CONTEUDO := 'INSERTING';
  ELSIF UPDATING THEN
     CONTEUDO := 'UPDATING';
  ELSE
     CONTEUDO := 'DELETE';
  END IF;
  
  insert into TESTE_TRIGGER(CONTEUDO) values (CONTEUDO);
END TR_TESTE;


Create Table TESTE_TRIGGER(
 SESSION_USER 		Varchar2(100)     DEFAULT SYS_CONTEXT('USERENV','SESSION_USER')		
,OS_USER 			    Varchar2(100)     DEFAULT SYS_CONTEXT('USERENV','OS_USER')			        
,HOST 				    Varchar2(100)     DEFAULT SYS_CONTEXT('USERENV','HOST')				      
,TERMINAL 			  Varchar2(100)     DEFAULT SYS_CONTEXT('USERENV','TERMINAL')			    
,IP_ADDRESS 		  Varchar2(100)     DEFAULT SYS_CONTEXT('USERENV','IP_ADDRESS')				  
,SESSIONID 			  Varchar2(100)     DEFAULT SYS_CONTEXT('USERENV','SESSIONID')			  
,CLIENT_INFO 		  Varchar2(100)     DEFAULT SYS_CONTEXT('USERENV','CLIENT_INFO')		    
,MODULE 			    Varchar2(100)     DEFAULT SYS_CONTEXT('USERENV','MODULE')					    
,ACTION 			    Varchar2(100)     DEFAULT SYS_CONTEXT('USERENV','ACTION')					    
,CURRENT_SQL 		  Varchar2(100)     DEFAULT SYS_CONTEXT('USERENV','CURRENT_SQL')     
,NETWORK_PROTOCOL Varchar2(100)     DEFAULT SYS_CONTEXT('USERENV','NETWORK_PROTOCOL')	
,conteudo  			  Varchar2(4000)
);
        
select * from TESTE_TRIGGER        