CREATE OR REPLACE TRIGGER TR_EST_MATMARCA_1
    After INSERT OR UPDATE OR DELETE OF 
        ACEITAMOVTOMATMARCA,
        CODIGOMATINT,
        CODIGOMARCAMAT ON MOBIBRASIL220525.EST_MATMARCA
    FOR EACH ROW
DECLARE 
   V_IDITEM NUMBER;    
BEGIN

     Dbms_Output.Put_Line('NEW ' || :NEW.CODIGOMARCAMAT);
     Dbms_Output.Put_Line('OLD ' || :OLD.CODIGOMARCAMAT);
  
   If (:New.CODIGOMARCAMAT = :Old.CODIGOMARCAMAT) Then
      Return;
   End If;

   BEGIN 
     SELECT NVL(MAX(ID),0)
       INTO V_IDITEM 
       FROM ITEM      
      WHERE IDITEMEXTERNO = NVL(:OLD.CODIGOMATINT,:NEW.CODIGOMATINT); 
      
   Dbms_Output.Put_Line( V_IDITEM );
   
      IF V_IDITEM > 0 AND (DELETING OR :NEW.ACEITAMOVTOMATMARCA = 'N') THEN
         DELETE FROM ITEMMARCA 
               WHERE IDITEM = V_IDITEM 
                 AND IDMARCA = :OLD.CODIGOMARCAMAT;         
         
      Elsif V_IDITEM = 0 AND :NEW.ACEITAMOVTOMATMARCA = 'S' THEN
            INSERT INTO ITEMMARCA
               (ID, IDMARCA, IDITEM)
            VALUES
               (SEQ_ITEMMARCA.NEXTVAL, :NEW.CODIGOMARCAMAT, V_IDITEM);
      END IF;      
   EXCEPTION
      WHEN OTHERS THEN
         LOG_INVENTARIO('TR_EST_MATMARCA', SQLERRM);
   END;   
END TR_EST_MATMARCA;

