SELECT
    CTE.ID_CTE                   AS ID,
    CTE.ID_DOCUMENTO             AS NUMERO,
    CTE.DATA_EMISSAO,
    CTE.CHAVE_DE_ACESSO          AS CHAVE_ACESSO,
    CTE.CONTEUDO                 AS CONTEUDO_CLOB,
    CTE.SISTEMA,
    CTE.STATUS_LOTE,
    TUR.CODINTNF                 AS TUR_CODIGO,
    TUR.VALORTOTALNF             AS TUR_VALOR_TOTAL,
    SAI.CODDOCTOESF              AS SAI_COD_DOCTO,
    SAI.VALORNF                  AS SAI_VALOR_NF,
    SAI.VLCONTABILSAIDA          AS SAI_VALOR_CONTABIL,
    SAI.ICMSVALORSAIDA           AS SAI_VALOR_ICMS,
    SAI.IPIVALORSAIDA            AS SAI_VALOR_IPI,
    VW_SAI.CODIGOEMPRESA         AS SAIFIL_COD_EMP,
    VW_SAI.CODIGOFL              AS SAIFIL_COD_FIL,
    VW_SAI.RSOCIALEMPRESA        AS SAIFIL_RSOCIAL,
    VW_SAI.INSCRICAOEMPRESA      AS SAIFIL_INSCRICAO,
    VW_SAI.NOMEFANTASIAEMPRESA   AS SAIFIL_NOMEFANTASIA,
    VW_TUR.CODIGOEMPRESA         AS TURFIL_COD_EMP,
    VW_TUR.CODIGOFL              AS TURFIL_COD_FIL,
    VW_TUR.RSOCIALEMPRESA        AS TURFIL_RSOCIAL,
    VW_TUR.INSCRICAOEMPRESA      AS TURFIL_INSCRICAO,
    VW_TUR.NOMEFANTASIAEMPRESA   AS TURFIL_NOMEFANTASIA
FROM BGM_CTE_OS CTE
    LEFT JOIN TUR_NOTAFISCAL TUR     ON TUR.CODINTNF = CTE.ID_DOCUMENTO
    LEFT JOIN ESFSAIDA SAI           ON SAI.CODDOCTOESF = TUR.CODDOCTOESF
    LEFT JOIN VW_FILIAL VW_SAI       ON VW_SAI.CODIGOEMPRESA = SAI.CODIGOEMPRESA AND VW_SAI.CODIGOFL = SAI.CODIGOFL
    LEFT JOIN VW_FILIAL VW_TUR       ON VW_TUR.CODIGOEMPRESA = TUR.CODIGOEMPRESA AND VW_TUR.CODIGOFL = TUR.CODIGOFL
ORDER BY CTE.ID_CTE;