SELECT
    INT_ESF.SEQUENCIA            AS SEQUENCIA,
    INT_ESF.CODINTNF             AS CODIGO_NOTA_FISCAL,
    INT_ESF.CODIGOMATINT         AS CODIGO_MATERIAL_INTERNO,
    INT_ESF.TIPONF               AS TIPO_NOTA,
    INT_ESF.CODDOCTOESF          AS CODIGO_DOCUMENTO_ESTOQUE,
    INT_ESF.CODSITTRIBUTARIA     AS CODIGO_SITUACAO_TRIBUTARIA,
    INT_ESF.CODCLASSFISC         AS CODIGO_CLASSIFICACAO_FISCAL,
    INT_ESF.CODOPERFISCAL        AS CODIGO_OPERACAO_FISCAL,
    INT_ESF.ICMSISENTA           AS ICMS_ISENTO,
    INT_ESF.ICMSOUTRAS           AS ICMS_OUTRAS,
    INT_ESF.VLCONTABIL           AS VALOR_CONTABIL
FROM BGM_NFINTEGRACAOESF INT_ESF
WHERE 1=1
ORDER BY INT_ESF.CODDOCTOESF, INT_ESF.SEQUENCIA;