SELECT
    SAI.CODDOCTOESF              AS COD_DOCTO_ESF
FROM ESFSAIDA SAI
WHERE 1=1
    -- AND SAI.CODIGOEMPRESA = :codigoEmpresa
    -- AND SAI.CODIGOFL      = :codigoFilial
    -- AND SAI.NRDOCSAIDA    = :nrDocSaida
    -- AND SAI.ITEMSAIDA     = :itemSaida
ORDER BY SAI.CODIGOEMPRESA, SAI.CODIGOFL, SAI.NRDOCSAIDA, SAI.ITEMSAIDA;