SELECT
    INT_NFSE.ID,
    INT_NFSE.SERIE_RPS           AS SERIE,
    INT_NFSE.NUMERO_NFSE_GERADO  AS NUMERO,
    INT_NFSE.CODIGO_VERIFICACAO  AS CHAVE_ACESSO,
    INT_NFSE.DATA_ENVIO          AS DATA_EMISSAO,
    INT_NFSE.CONTEUDO_XML        AS CONTEUDO_CLOB,
    INT_NFSE.MODULO,
    INT_NFSE.STATUS,
    /* manutencaoDocumentosEsf (FTA001) join codigo=idNotaFiscal e serie */
    FTA.RECNUM                   AS MANUT_CODIGO,
    FTA.ID_CTE                   AS MANUT_ID_CTE,
    FTA.SERIE                    AS MANUT_SERIE,
    /* esfIssEntraIntegrador (ESFISS via DOCUMENTOINI = NUMERO_NFSE_GERADO) */
    ISS.VLRSERVICO               AS ISS_VALOR_SERVICO,
    ISS.VALORISS                 AS ISS_VALOR_ISS,
    ISS.VALORIRRF                AS ISS_VALOR_IRRF,
    ISS.VALORPIS                 AS ISS_VALOR_PIS,
    ISS.VALORCOFINS              AS ISS_VALOR_COFINS,
    ISS.VALORINSS                AS ISS_VALOR_INSS,
    ISS.VALORCSLL                AS ISS_VALOR_CSLL,
    VW_ISS.CODIGOEMPRESA         AS ISSFIL_COD_EMP,
    VW_ISS.CODIGOFL              AS ISSFIL_COD_FIL,
    VW_ISS.RSOCIALEMPRESA        AS ISSFIL_RSOCIAL,
    VW_ISS.INSCRICAOEMPRESA      AS ISSFIL_INSCRICAO,
    VW_ISS.NOMEFANTASIAEMPRESA   AS ISSFIL_NOMEFANTASIA
FROM BGM_INTEGRADOR_NFSE INT_NFSE
    LEFT JOIN FTA001 FTA         ON FTA.RECNUM = INT_NFSE.ID_NOTA_FISCAL
                                AND FTA.SERIE  = INT_NFSE.SERIE_RPS
    LEFT JOIN ESFISS ISS         ON ISS.DOCUMENTOINI = INT_NFSE.NUMERO_NFSE_GERADO
    LEFT JOIN VW_FILIAL VW_ISS   ON VW_ISS.CODIGOEMPRESA = ISS.CODIGOEMPRESA AND VW_ISS.CODIGOFL = ISS.CODIGOFL
WHERE 1=1	
ORDER BY INT_NFSE.ID;