SELECT
    ENT.CODIGOEMPRESA            AS CODIGO_EMPRESA,
    ENT.CODIGOFL                 AS CODIGO_FILIAL,
    ENT.CODIGOFORN               AS CODIGO_FORNECEDOR,
    ENT.NRDOCENTRA               AS NUMERO_DOCUMENTO,
    ENT.ITEMENTRA                AS ITEM_DOCUMENTO,
    ENT.CODDOCTOESF              AS CODIGO_DOCUMENTO_ESF,
    INT_ESF.SEQUENCIA            AS SEQUENCIA,
    INT_ESF.CODINTNF             AS CODIGO_NF_INTERNA,
    INT_ESF.CODIGOMATINT         AS CODIGO_MATERIAL_INTERNO,
    INT_ESF.TIPONF               AS TIPO_NOTA_FISCAL,
    INF.CODIGOMATINT             AS CODIGO_INT_MATERIAL,
    INF.DESCRICAOITEMNF          AS DESCRICAO_MATERIAL,
    INF.QTDEITENSNF              AS QUANTIDADE_ITEM,
    INF.VALORTOTALITENSNF        AS VALOR_TOTAL_ITEM,
    INT_ESF.CODSITTRIBUTARIA     AS CODIGO_SITUACAO_TRIBUTARIA,
    INT_ESF.CODCLASSFISC         AS CODIGO_CLASSIFICACAO_FISCAL,
    INT_ESF.CODOPERFISCAL        AS CODIGO_OPERACAO_FISCAL,
    INT_ESF.ICMSISENTA           AS ICMS_ISENTO,
    INT_ESF.ICMSOUTRAS           AS ICMS_OUTRAS,
    INT_ESF.VLCONTABIL           AS VALOR_CONTABIL
FROM ESFENTRA ENT
    LEFT JOIN BGM_NFINTEGRACAOESF INT_ESF ON INT_ESF.CODDOCTOESF = ENT.CODDOCTOESF
    LEFT JOIN EST_ITENSNF INF             ON INF.CODINTNF = INT_ESF.CODINTNF
                                         AND INF.CODIGOMATINT = INT_ESF.CODIGOMATINT
WHERE 1=1
ORDER BY ENT.CODDOCTOESF, INT_ESF.SEQUENCIA;