--codModelo == '63_E'

SELECT
    '63_E'                       AS codModelo
    DOC.ID,
    DOC.SERIE,
    DOC.NUMERO,
    DOC.DATA_EMISSAO,
    DOC.CHAVEDEACESSO            AS CHAVE_ACESSO,
    DOC.CONTEUDO_XML             AS CONTEUDO_CLOB,
    DOC.SISTEMA,
    DOC.SISTEMA_IMPORTACAO,
    BNF.CODINTNF                 AS BGMNF_CODIGO,
    BNF.VALORTOTALNF             AS BGMNF_VALOR_TOTAL,
    BNF_ISS.CODISSINT            AS BGMNFISS_CODIGO,
    BNF_ISS.VLRSERVICO           AS BGMNFISS_VALOR_SERVICO,
    BNF_ISS.VALORISS             AS BGMNFISS_VALOR_ISS,
    BNF_ISS.VALORIRRF            AS BGMNFISS_VALOR_IRRF,
    BNF_ISS.VALORPIS             AS BGMNFISS_VALOR_PIS,
    BNF_ISS.VALORCOFINS          AS BGMNFISS_VALOR_COFINS,
    BNF_ISS.SISTEMA              AS BGMNFISS_SISTEMA,
    VW_BISS.CODIGOEMPRESA        AS BGMNFISSFIL_COD_EMP,
    VW_BISS.CODIGOFL             AS BGMNFISSFIL_COD_FIL,
    VW_BISS.RSOCIALEMPRESA       AS BGMNFISSFIL_RSOCIAL,
    VW_BISS.INSCRICAOEMPRESA     AS BGMNFISSFIL_INSCRICAO,
    VW_BISS.NOMEFANTASIAEMPRESA  AS BGMNFISSFIL_NOMEFANTASIA,
    VW_BNF.CODIGOEMPRESA         AS BGMNFFIL_COD_EMP,
    VW_BNF.CODIGOFL              AS BGMNFFIL_COD_FIL,
    VW_BNF.RSOCIALEMPRESA        AS BGMNFFIL_RSOCIAL,
    VW_BNF.INSCRICAOEMPRESA      AS BGMNFFIL_INSCRICAO,
    VW_BNF.NOMEFANTASIAEMPRESA   AS BGMNFFIL_NOMEFANTASIA,
    NFM.NRMONTAGEM               AS NFM_NRMONTAGEM,
    NFM.VALOR                    AS NFM_VALOR,
    NFM_ISS.CODISSINT            AS NFMISS_CODIGO,
    NFM_ISS.VLRSERVICO           AS NFMISS_VALOR_SERVICO,
    NFM_ISS.VALORISS             AS NFMISS_VALOR_ISS,
    NFM_ISS.VALORIRRF            AS NFMISS_VALOR_IRRF,
    NFM_ISS.VALORPIS             AS NFMISS_VALOR_PIS,
    NFM_ISS.VALORCOFINS          AS NFMISS_VALOR_COFINS,
    NFM_ISS.SISTEMA              AS NFMISS_SISTEMA,
    VW_NMISS.CODIGOEMPRESA       AS NFMISSFIL_COD_EMP,
    VW_NMISS.CODIGOFL            AS NFMISSFIL_COD_FIL,
    VW_NMISS.RSOCIALEMPRESA      AS NFMISSFIL_RSOCIAL,
    VW_NMISS.INSCRICAOEMPRESA    AS NFMISSFIL_INSCRICAO,
    VW_NMISS.NOMEFANTASIAEMPRESA AS NFMISSFIL_NOMEFANTASIA,
    ISS.CODISSINT                AS ISS_CODIGO,
    ISS.VLRSERVICO               AS ISS_VALOR_SERVICO,
    ISS.VALORISS                 AS ISS_VALOR_ISS,
    ISS.VALORIRRF                AS ISS_VALOR_IRRF,
    ISS.VALORPIS                 AS ISS_VALOR_PIS,
    ISS.VALORCOFINS              AS ISS_VALOR_COFINS,
    ISS.VALORINSS                AS ISS_VALOR_INSS,
    ISS.VALORCSLL                AS ISS_VALOR_CSLL,
    ISS.SISTEMA                  AS ISS_SISTEMA,
    VW_ISS.CODIGOEMPRESA         AS ISSFIL_COD_EMP,
    VW_ISS.CODIGOFL              AS ISSFIL_COD_FIL,
    VW_ISS.RSOCIALEMPRESA        AS ISSFIL_RSOCIAL,
    VW_ISS.INSCRICAOEMPRESA      AS ISSFIL_INSCRICAO,
    VW_ISS.NOMEFANTASIAEMPRESA   AS ISSFIL_NOMEFANTASIA
FROM ESF_DOCUMENTO_ELETRONICO DOC
    LEFT JOIN BGM_NOTAFISCAL BNF       ON BNF.CODINTNF = DOC.CODINTNF_BGMNF
    LEFT JOIN ESFISS_ENTRA BNF_ISS     ON BNF_ISS.CODINTNF = BNF.CODINTNF
    LEFT JOIN VW_FILIAL VW_BISS        ON VW_BISS.CODIGOEMPRESA = BNF_ISS.CODIGOEMPRESA AND VW_BISS.CODIGOFL = BNF_ISS.CODIGOFL
    LEFT JOIN VW_FILIAL VW_BNF         ON VW_BNF.CODIGOEMPRESA = BNF.CODIGOEMPRESA AND VW_BNF.CODIGOFL = BNF.CODIGOFL
    LEFT JOIN EST_NFSERVMONTAGEM NFM   ON NFM.CODINTNF = DOC.CODINTNF_BGMNF
    LEFT JOIN ESFISS_ENTRA NFM_ISS     ON NFM_ISS.CODINTNF = NFM.CODINTNF
    LEFT JOIN VW_FILIAL VW_NMISS       ON VW_NMISS.CODIGOEMPRESA = NFM_ISS.CODIGOEMPRESA AND VW_NMISS.CODIGOFL = NFM_ISS.CODIGOFL
    LEFT JOIN ESFISS_ENTRA ISS         ON ISS.DOCUMENTOINI = DOC.NUMERO
    LEFT JOIN VW_FILIAL VW_ISS         ON VW_ISS.CODIGOEMPRESA = ISS.CODIGOEMPRESA AND VW_ISS.CODIGOFL = ISS.CODIGOFL
WHERE 1=1	
ORDER BY DOC.ID;