SELECT
    XT.ID_NFE_CTE                AS ID,
    XT.SERIE,
    XT.NUMERO,
    XT.DATAEMISSAO               AS DATA_EMISSAO,
    XT.DATAGEROU                 AS DATA_GEROU,
    XT.CHAVEDEACESSO             AS CHAVE_ACESSO,
    XT.TIPO_NOTA,
    XT.CONFERIDO,
    XT.CONTEUDO_CLOB,
    XT.CONTEUDOXML               AS CONTEUDO_XML,
    XT.CODINTNF_ESFNF            AS CODIGO_INT_NF_ESF,
    XT.CODINTNF_BGMNF            AS CODIGO_INT_NF_BGM,
    XT.SISTEMA,

    TUR.CODINTNF                 AS TUR_CODIGO,
    TUR.VALORTOTALNF             AS TUR_VALOR_TOTAL,

    VWFT.CODIGOEMPRESA           AS TURFIL_COD_EMP,
    VWFT.CODIGOFL                AS TURFIL_COD_FIL,
    VWFT.RSOCIALEMPRESA          AS TURFIL_RSOCIAL,
    VWFT.INSCRICAOEMPRESA        AS TURFIL_INSCRICAO,
    VWFT.NOMEFANTASIAEMPRESA     AS TURFIL_NOMEFANTASIA,

    ENT_T.CODIGOEMPRESA          AS TURENT_COD_EMP,
    ENT_T.ICMSVALORENTRA         AS TURENT_VALOR_ICMS,
    ENT_T.IPIVALORENTRA          AS TURENT_VALOR_IPI,

    VW_TE.CODIGOEMPRESA          AS TURENTFIL_COD_EMP,
    VW_TE.CODIGOFL               AS TURENTFIL_COD_FIL,
    VW_TE.RSOCIALEMPRESA         AS TURENTFIL_RSOCIAL,
    VW_TE.INSCRICAOEMPRESA       AS TURENTFIL_INSCRICAO,
    VW_TE.NOMEFANTASIAEMPRESA    AS TURENTFIL_NOMEFANTASIA,

    BNF.CODINTNF                 AS BGMNF_CODIGO,
    BNF.VALORTOTALNF             AS BGMNF_VALOR_TOTAL,
    BGM_INT.SEQUENCIA            AS BGMINT_SEQUENCIA,
    VW_BNF.CODIGOEMPRESA         AS BGMNFFIL_COD_EMP,
    VW_BNF.CODIGOFL              AS BGMNFFIL_COD_FIL,
    VW_BNF.RSOCIALEMPRESA        AS BGMNFFIL_RSOCIAL,
    VW_BNF.INSCRICAOEMPRESA      AS BGMNFFIL_INSCRICAO,
    VW_BNF.NOMEFANTASIAEMPRESA   AS BGMNFFIL_NOMEFANTASIA,

    NFT.CODINTNF                 AS NFT_CODIGO,
    NFT.VLRLIQUIDO               AS NFT_VALOR_LIQUIDO,
    NFT_INT.SEQUENCIA            AS NFTINT_SEQUENCIA,

    NFC.CODINTNF                 AS NFC_CODIGO_NF,
    NFC.VALORICMS                AS NFC_VALOR_ICMS,
    NFC_INT.SEQUENCIA            AS NFCINT_SEQUENCIA,

    ENF.CODINTNF                 AS ESFNF_CODIGO,
    ENF.VALORTOTAL               AS ESFNF_VALOR_TOTAL,
    VW_ENF.CODIGOEMPRESA         AS ESFNFFIL_COD_EMP,
    VW_ENF.CODIGOFL              AS ESFNFFIL_COD_FIL,
    VW_ENF.RSOCIALEMPRESA        AS ESFNFFIL_RSOCIAL,
    VW_ENF.INSCRICAOEMPRESA      AS ESFNFFIL_INSCRICAO,
    VW_ENF.NOMEFANTASIAEMPRESA   AS ESFNFFIL_NOMEFANTASIA,
    ENT_NF.CODDOCTOESF           AS ESFNFENT_COD_DOCTO,
    ENT_NF.ICMSVALORENTRA        AS ESFNFENT_VALOR_ICMS,
    ENT_NF.VALOR_ICMS_MONO       AS ESFNFENT_VALOR_ICMS_MONO,
    ENT_NF.IPIVALORENTRA         AS ESFNFENT_VALOR_IPI,
    ENT_NF.VLCONTABILENTRA       AS ESFNFENT_VALOR_CONTABIL,
    VW_NE.CODIGOEMPRESA          AS ESFNFENTFIL_COD_EMP,
    VW_NE.CODIGOFL               AS ESFNFENTFIL_COD_FIL,
    VW_NE.RSOCIALEMPRESA         AS ESFNFENTFIL_RSOCIAL,
    VW_NE.INSCRICAOEMPRESA       AS ESFNFENTFIL_INSCRICAO,
    VW_NE.NOMEFANTASIAEMPRESA    AS ESFNFENTFIL_NOMEFANTASIA,

    EXT.CODDOCTOESF              AS XMLENT_COD_DOCTO,
    EXT.ICMSVALORENTRA           AS XMLENT_VALOR_ICMS,
    EXT.VALOR_ICMS_MONO          AS XMLENT_VALOR_ICMS_MONO,
    EXT.IPIVALORENTRA            AS XMLENT_VALOR_IPI,
    EXT.VLCONTABILENTRA          AS XMLENT_VALOR_CONTABIL,
    VW_XE.CODIGOEMPRESA          AS XMLENTFIL_COD_EMP,
    VW_XE.CODIGOFL               AS XMLENTFIL_COD_FIL,
    VW_XE.RSOCIALEMPRESA         AS XMLENTFIL_RSOCIAL,
    VW_XE.INSCRICAOEMPRESA       AS XMLENTFIL_INSCRICAO,
    VW_XE.NOMEFANTASIAEMPRESA    AS XMLENTFIL_NOMEFANTASIA,

    FRE.CODINTNF                 AS FRE_CODIGO,
    FRE.NUMERONF                 AS FRE_NUMERO_NF,
    FRE.VALORLIQUIDO             AS FRE_VALOR_LIQUIDO,
    FRE.VALORBRUTO               AS FRE_VALOR_BRUTO
FROM BGM_XML_TERCEIROS XT
    LEFT JOIN TUR_NOTAFISCAL TUR        ON TUR.CODINTNF = XT.CODINTNF_BGMNF
    LEFT JOIN VW_FILIAL VWFT            ON VWFT.CODIGOEMPRESA = TUR.CODIGOEMPRESA AND VWFT.CODIGOFL = TUR.CODIGOFL
    LEFT JOIN ESFENTRA ENT_T            ON ENT_T.CODDOCTOESF = TUR.CODDOCTOESF
    LEFT JOIN VW_FILIAL VW_TE           ON VW_TE.CODIGOEMPRESA = ENT_T.CODIGOEMPRESA AND VW_TE.CODIGOFL = ENT_T.CODIGOFL
    LEFT JOIN BGM_NOTAFISCAL BNF        ON BNF.CODINTNF = XT.CODINTNF_BGMNF
    LEFT JOIN BGM_NFINTEGRACAOESF BGM_INT ON BGM_INT.CODINTNF = BNF.CODINTNF
    LEFT JOIN VW_FILIAL VW_BNF          ON VW_BNF.CODIGOEMPRESA = BNF.CODIGOEMPRESA AND VW_BNF.CODIGOFL = BNF.CODIGOFL
    LEFT JOIN EST_NOTAFISCAL_TRANS NFT  ON NFT.CODINTNF = XT.CODINTNF_BGMNF
    LEFT JOIN BGM_NFINTEGRACAOESF NFT_INT ON NFT_INT.CODINTNF = NFT.CODINTNF
    LEFT JOIN EST_NFCOMPLEMENTAR NFC    ON NFC.CODINTNF = XT.CODINTNF_BGMNF
    LEFT JOIN BGM_NFINTEGRACAOESF NFC_INT ON NFC_INT.CODINTNF = NFC.CODINTNF
    LEFT JOIN ESFNOTAFISCAL ENF         ON ENF.CHAVEDEACESSO = XT.CHAVEDEACESSO
    LEFT JOIN VW_FILIAL VW_ENF          ON VW_ENF.CODIGOEMPRESA = ENF.CODIGOEMPRESA AND VW_ENF.CODIGOFL = ENF.CODIGOFL
    LEFT JOIN ESFENTRA ENT_NF           ON ENT_NF.CODDOCTOESF = ENF.CODDOCTOESF
    LEFT JOIN VW_FILIAL VW_NE           ON VW_NE.CODIGOEMPRESA = ENT_NF.CODIGOEMPRESA AND VW_NE.CODIGOFL = ENT_NF.CODIGOFL
    LEFT JOIN ESFENTRA EXT              ON EXT.CODDOCTOESF = XT.CODDOCTOESF
    LEFT JOIN VW_FILIAL VW_XE           ON VW_XE.CODIGOEMPRESA = EXT.CODIGOEMPRESA AND VW_XE.CODIGOFL = EXT.CODIGOFL
    LEFT JOIN FREM_NOTAFISCAL FRE       ON FRE.CODINTNF = XT.CODINTNF_ESFNF
WHERE 1=1	
ORDER BY XT.ID_NFE_CTE;