SELECT
    ENT.ICMSBASEENTRA            AS BASE_CALCULO_ICMS,
    ENT.ICMSALIQENTRA            AS ALIQUOTA_ICMS,
    ENT.ICMSVALORENTRA           AS VALOR_ICMS,
    ENT.VALOR_ICMS_MONO          AS VALOR_ICMS_MONO,
    ENT.IPIBASEENTRA             AS BASE_CALCULO_IPI,
    ENT.IPIVALORENTRA            AS VALOR_IPI,
    ENT.IPIALIQENTRA             AS ALIQUOTA_IPI
FROM ESFENTRA ENT
WHERE 1=1
    -- AND ENT.CODIGOEMPRESA = :codigoEmpresa
    -- AND ENT.CODIGOFL      = :codigoFilial
    -- AND ENT.CODDOCTOESF   = :codigoDocumentoEsf
ORDER BY ENT.CODIGOEMPRESA, ENT.CODIGOFL, ENT.NRDOCENTRA, ENT.ITEMENTRA;