-- 1
// If (pUsuario = 'GLOBUS') Or (pUsuario = 'MANAGER') Then
 SELECT F.CODIGOFL
      , A.RSOCIALEMPRESA
      , A.CHECKSUMEMPRESA
      , A.INSCRICAOEMPRESA
      , A.NOMEFANTASIAEMPRESA
      , A.CODINTEMPAUT
      , F.CODIGOUF
      , F.CIDADEFL
      , C.SISTEMA 
   FROM CTR_FILIAL              F
      , CTR_EMPAUTORIZADAS      A
      , CTR_AUTORIZACAOSISTEMAS C 
  WHERE F.CODIGOEMPRESA = 1
    AND F.CODINTEMPAUT  = A.CODINTEMPAUT 
    AND F.CODINTEMPAUT  = C.CODINTEMPAUT 
    AND C.SISTEMA       = 'ACD'
 ORDER BY F.CODIGOFL;
-- 2
SELECT F.CODIGOFL
     , A.RSOCIALEMPRESA
     , A.CHECKSUMEMPRESA
     , A.INSCRICAOEMPRESA
     , A.NOMEFANTASIAEMPRESA
     , A.CODINTEMPAUT
     , F.CODIGOUF
     , F.CIDADEFL
     , C.SISTEMA 
  FROM CTR_FILIAL              F
     , CTR_EMPAUTORIZADAS      A
     , CTR_AUTORIZACAOSISTEMAS C
     , CTR_AUTORIZACAOUSUARIOS AU
     , CTR_CADASTRODEUSUARIOS  CADU
     , CTR_GRUPOUSUARIOS       GU 
 WHERE F.CODIGOEMPRESA = 1
   AND F.CODINTEMPAUT  = A.CODINTEMPAUT 
   AND F.CODINTEMPAUT  = C.CODINTEMPAUT 
   AND F.CODINTEMPAUT  = AU.CODINTEMPAUT 
   AND AU.CODIGOGRPUSU = CADU.CODIGOGRPUSU 
   AND GU.CODIGOGRPUSU = CADU.CODIGOGRPUSU 
   AND C.SISTEMA       = 'ACD'
   AND CADU.USUARIO    = 'ABINALDO'
ORDER BY F.CODIGOFL;