DECLARE
  V_EXIST   INTEGER;
  V_NEXTVAL INTEGER;
BEGIN
  V_NEXTVAL := 0;
  
  SELECT COUNT(1)
    INTO V_EXIST
    FROM USER_SEQUENCES
   WHERE SEQUENCE_NAME = 'SQ_RHTAON_DIALOGO_TITULO_USUARIO';
  
  IF V_EXIST > 0 THEN
  BEGIN
      SELECT SQ_RHTAON_DIALOGO_TITULO_USUARIO.NEXTVAL
        INTO V_NEXTVAL
        FROM DUAL;

      EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_RHTAON_DIALOGO_TITULO_USUARIO';
  END;
  END IF;
  
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SQ_RHTAON_DIALOGO_TITULO_USUAR START WITH ' || TO_CHAR(V_NEXTVAL + 10) || ' INCREMENT BY 1 NOCACHE';
END;