SELECT * FROM bgm_token

SELECT b.codigolinha,  a.* 
FROM RDA_PLANEJAMENTO a
INNER JOIN bgm_cadlinhas b ON a.codintlinha = b.codintlinha
;

SELECT * FROM RDA_PLANEJAMENTO_TRECHOS;
SELECT * FROM rda_planejamento_paradas


SELECT * FROM RDA_GRUPO_ESCALA;
SELECT * FROM RDA_GRUPO_ESCALA_TRECHOS;
SELECT * FROM RDA_GRUPO_ESCALA_FUNCIONARIOS;

SELECT * FROM RDA_ESCALA_DIARIA;
SELECT * FROM RDA_ESCALA_DIARIA_TRECHOS;