ALTER TABLE ESF_DOCUMENTO_ELETRONICO  ADD (CONFERIDO NUMBER(1));
ALTER TABLE BGM_XML_TERCEIROS         ADD (CONFERIDO NUMBER(1));
ALTER TABLE BGM_CTE_OS                ADD (CONFERIDO NUMBER(1));
ALTER TABLE BGM_NOTAFISCAL_ELETRONICA ADD (CONFERIDO NUMBER(1));
ALTER TABLE BGM_CTRC_ELETRONICO       ADD (CONFERIDO NUMBER(1));
ALTER TABLE BGM_INTEGRADOR_NFSE       ADD (CONFERIDO NUMBER(1));