ALTER TABLE BGM_XML_TERCEIROS         ADD (ETAPA NUMBER(1));
ALTER TABLE ESF_DOCUMENTO_ELETRONICO  ADD (ETAPA NUMBER(1));
ALTER TABLE BGM_CTE_OS                ADD (ETAPA NUMBER(1));
ALTER TABLE BGM_NOTAFISCAL_ELETRONICA ADD (ETAPA NUMBER(1));
ALTER TABLE BGM_CTRC_ELETRONICO       ADD (ETAPA NUMBER(1));
ALTER TABLE BGM_INTEGRADOR_NFSE       ADD (ETAPA NUMBER(1));