ALTER TABLE BGM_XML_TERCEIROS         ADD (ETAPA_IMPORTACAO NUMBER(1));
ALTER TABLE ESF_DOCUMENTO_ELETRONICO  ADD (ETAPA_IMPORTACAO NUMBER(1));
ALTER TABLE BGM_CTE_OS                ADD (ETAPA_IMPORTACAO NUMBER(1));
ALTER TABLE BGM_NOTAFISCAL_ELETRONICA ADD (ETAPA_IMPORTACAO NUMBER(1));
ALTER TABLE BGM_CTRC_ELETRONICO       ADD (ETAPA_IMPORTACAO NUMBER(1));
ALTER TABLE BGM_INTEGRADOR_NFSE       ADD (ETAPA_IMPORTACAO NUMBER(1));