SELECT 
a.*,
'drop '||  a.object_type || ' '|| a.object_name ||';'
FROM user_Objects a
WHERE 
a.GENERATED = 'N' AND  a.object_type != 'INDEX' -- AND a.object_type != 'JOB'
--a.object_type = 'JOB'
ORDER BY a.object_id DESC



SELECT COUNT(*) FROM user_Objects a
WHERE  a.object_name IN (
'JOB_GPS','PR_GPS','TR_PLT_OCORRENCIASROD','TR_FLP_DOCUMENTOS','TR_RDA_ESCALA_DIARIA_TRECHOS','TR_RDA_PLANEJAMENTO_PARADAS','TR_RDA_PLANEJAMENTO_TRECHOS','TR_RDA_PLANEJAMENTO','TR_T_ESC_AFASTAMENTO',
'TR_FLP_AFASTADOS','TR_T_ESC_SEQUENCIAFOLGAFUNC','TR_T_ESC_SUBSTFOLGA','TR_FLP_FERIAS','TR_MAN_OS','TR_ARR_SETORES','TR_CTR_CADASTRODEUSUARIOS','TR_FRT_CADVEICULOS','TR_FRT_MODCARROC',
'TR_BGM_CADLINHAS','TR_T_ESC_LOCALIDADE','TR_FLP_HISTORICOSALARIAL','TR_T_ESC_PARAMFUNC','TR_FLP_FUNCIONARIOS','TR_CTR_FILIAL','TR_CTR_CADEMP','TR_CTR_EMPAUTORIZADAS',
'TR_ROD_PLANEJAMENTO_TRECHOS','TR_ROD_PLANEJAMENTO_PARADAS','TR_ROD_PLANEJAMENTO','TR_ROD_ESCALA_DIARIA_TRECHOS','PR_ROD_PLANEJAMENTO_TRECHOS','PR_ROD_PLANEJAMENTO_PARADAS',
'PR_ROD_PLANEJAMENTO','PR_ROD_DIARIA_TRECHO_EXTRA','PR_ROD_DIARIA_TRECHOS','PR_ROD_DIARIA','PR_DIARIA_TRECHO_EXTRA','PR_RDA_PLANEJAMENTO_PARADAS','PR_RDA_PLANEJAMENTO_TRECHOS','PR_RDA_PLANEJAMENTO',
'PR_RDA_DIARIA_TRECHOS','PR_RDA_DIARIA','PR_FUNCIONARIOINFORMACAO','PR_T_ESC_PARAMFUNC','FC_RETORNAR_IDLINHA','FC_RETORNAR_IDSERVICO','FC_RETORNAR_IDVEICULO','FC_RETORNAR_IDFUNCIONARIO',
'FC_RETORNAR_LOCALIDADES','FC_RETORNAR_IDHORARIO','T_PROGRAMADO','T_LOCALIDADE','SEQ_NOTIFICACAOUSUARIO','NOTIFICACAOUSUARIO','SEQ_NOTIFICACAO','NOTIFICACAO',
'SEQ_GPS','GPS','SEQ_REALIZADATRECHOOCORCOMENT','REALIZADATRECHOOCORCOMENT','SEQ_REALIZADATRECHOOCOR','REALIZADATRECHOOCOR','SEQ_REALIZADATRECHO','REALIZADATRECHO',
'SEQ_OCORRENCIAMOTIVO','OCORRENCIAMOTIVO','SEQ_DIARIATRECHOEXTRA','DIARIATRECHOEXTRA','SEQ_DIARIATRECHO','DIARIATRECHO','SEQ_DIARIA','DIARIA','SEQ_PROGRAMADOPARADA',
'PROGRAMADOPARADA','SEQ_PROGRAMADOTRECHO','PROGRAMADOTRECHO','SEQ_PROGRAMADO','PROGRAMADO','SEQ_USUARIOSETOR','USUARIOSETOR','SEQ_SETORLOCALIDADE','SETORLOCALIDADE','SEQ_SETOR','SETOR',
'SEQ_USUARIO','USUARIO','SEQ_VEICULOINFORMACAO','VEICULOINFORMACAO','SEQ_VEICULO','VEICULO','SEQ_TECNOLOGIA','TECNOLOGIA','SEQ_FUNCIONARIOINFORMACAO','FUNCIONARIOINFORMACAO','SEQ_FUNCIONARIO','FUNCIONARIO',
'SEQ_SERVICO','SERVICO','SEQ_LOCALIDADE','LOCALIDADE','SEQ_HORARIO','HORARIO','SEQ_LINHA','LINHA','SEQ_FILIAL','FILIAL','SEQ_EMPRESA',
'EMPRESA','SEQ_EMPRESAAUTORIZADA','EMPRESAAUTORIZADA','JOB_DESABILITA_TRIGGER','PR_DESABILITA_TRIGGER','PR_LOG_INTEGRACAO','LOG_INTEGRACAO','VERSIONINFO')