//------------------------ Criando tipo
CREATE OR REPLACE TYPE T_NOME_OBJETO AS OBJECT
( 
  COLUNA1        RAW(16),
  COLUNA2        VARCHAR2(200)
);

//------------------------ Criando função
CREATE OR REPLACE FUNCTION FC_RETORNAR_DADOS( P_CDFILA NUMBER) RETURN T_NOME_OBJETO AS
  V_RETORNO T_NOME_OBJETO;

  CURSOR C_DADOS IS
                WITH OBJS AS (
               SELECT
                  O.CDOBJETO,O.CDFILA,O.CDFLUXOTRABALHO,O.NUSEQHIST,O.CDFORO,O.CDVARA,O.CDFOROVARA
                 FROM SAJ.EWFLOBJETOFILA O
               WHERE O.CDFILA = P_CDFILA)      
            SELECT
              P.NUPROCESSO,P.CDPROCESSO,P.CDOBJETO,OFI.CDFLUXOTRABALHO,OFI.CDFILA,PA.CDPROCESSOAPENSO AS CDPROCESSOPETICAO,PD.CDDOCUMENTO,D.CDTIPODOCDIGITAL,TD.DETIPODOCDIGITAL,ID.BLIMAGEM
            FROM  OBJS O
               JOIN SAJ.EWFLOBJETOFILA OFI ON      OFI.CDOBJETO = O.CDOBJETO AND      OFI.CDFILA = O.CDFILA AND     OFI.CDFLUXOTRABALHO = O.CDFLUXOTRABALHO
               JOIN SAJ.EFPGPROCESSO P ON     P.CDPROCESSO = OFI.CDPROCESSO     JOIN SAJ.EFPGPROCESSOAPENSO PA     ON PA.CDPROCESSO = P.CDPROCESSO
               JOIN SAJ.EDIGPAGINADOC PD     ON PD.CDPROCESSOORIGEM = PA.CDPROCESSOAPENSO   JOIN SAJ.EDIGDOCUMENTO D     ON D.CDDOCUMENTO = PD.CDDOCUMENTO
               JOIN SAJ.EDIGTIPODOCDIGITAL TD     ON TD.CDTIPODOCDIGITAL = D.CDTIPODOCDIGITAL
               JOIN SAJ.EDIGIMAGEMDOC ID     ON ID.CDDOCUMENTO = D.CDDOCUMENTO;
BEGIN
     IF  (P_CDFILA = 0)          THEN
     BEGIN
          RAISE_APPLICATION_ERROR(
                                  	-20000,                           ---- NUMERO DO ERRO ORACLE
                               			'ssssss');                       ---- MENSAGEM    
     END;;

  V_RETORNO := T_NOME_OBJETO();

 FORALL
 
  FOR R_DADOS IN C_DADOS LOOP

    V_RETORNO.EXTEND;

    V_RETORNO(V_RETORNO.COUNT) := T_NOME_OBJETO(
	  R_DADOS.COLUNA1,
    R_DADOS.COLUNA2
     );
  END LOOP;
  
  RETURN V_RETORNO;
END;
//------------------------ Exemplo de utilização

Select *
From Table(FC_RETORNAR_DADOS(15))  a